// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Data.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250819035516_InitClean")]
    partial class InitClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Domain.Entities.AreaDishPrices", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CustomPrice")
                        .HasColumnType("float");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("AreaId", "DishId", "EffectiveDate")
                        .HasDatabaseName("IX_AreaDishPrices_AreaId_DishId_EffectiveDate");

                    b.ToTable("AreaDishPrices");

                    b.HasData(
                        new
                        {
                            Id = "ADP001",
                            AreaId = "AREA001",
                            CustomPrice = 350000.0,
                            DishId = "DISH001",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP002",
                            AreaId = "AREA001",
                            CustomPrice = 75000.0,
                            DishId = "DISH004",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP003",
                            AreaId = "AREA003",
                            CustomPrice = 402500.0,
                            DishId = "DISH001",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP004",
                            AreaId = "AREA003",
                            CustomPrice = 207000.0,
                            DishId = "DISH002",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP005",
                            AreaId = "AREA003",
                            CustomPrice = 322000.0,
                            DishId = "DISH003",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP006",
                            AreaId = "AREA003",
                            CustomPrice = 287500.0,
                            DishId = "DISH007",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP007",
                            AreaId = "AREA002",
                            CustomPrice = 185250.0,
                            DishId = "DISH008",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP008",
                            AreaId = "AREA002",
                            CustomPrice = 156750.0,
                            DishId = "DISH009",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP009",
                            AreaId = "AREA002",
                            CustomPrice = 137750.0,
                            DishId = "DISH010",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP010",
                            AreaId = "AREA004",
                            CustomPrice = 75000.0,
                            DishId = "DISH004",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP011",
                            AreaId = "AREA004",
                            CustomPrice = 65000.0,
                            DishId = "DISH005",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP012",
                            AreaId = "AREA004",
                            CustomPrice = 85000.0,
                            DishId = "DISH006",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP013",
                            AreaId = "AREA001",
                            CustomPrice = 65000.0,
                            DishId = "DISH011",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP014",
                            AreaId = "AREA001",
                            CustomPrice = 85000.0,
                            DishId = "DISH014",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP015",
                            AreaId = "AREA001",
                            CustomPrice = 25000.0,
                            DishId = "DISH015",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP016",
                            AreaId = "AREA003",
                            CustomPrice = 71500.0,
                            DishId = "DISH011",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP017",
                            AreaId = "AREA003",
                            CustomPrice = 82500.0,
                            DishId = "DISH012",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ADP018",
                            AreaId = "AREA003",
                            CustomPrice = 93500.0,
                            DishId = "DISH014",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Areas", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .IsUnique();

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = "AREA001",
                            AreaId = "A001",
                            AreaName = "Tầng Trệt - Khu A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực tầng trệt, phù hợp cho gia đình",
                            IsActive = true
                        },
                        new
                        {
                            Id = "AREA002",
                            AreaId = "A002",
                            AreaName = "Tầng Trệt - Khu B",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực tầng trệt, gần cửa sổ",
                            IsActive = true
                        },
                        new
                        {
                            Id = "AREA003",
                            AreaId = "A003",
                            AreaName = "Tầng 2 - Khu VIP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực VIP tầng 2, view đẹp",
                            IsActive = true
                        },
                        new
                        {
                            Id = "AREA004",
                            AreaId = "A004",
                            AreaName = "Tầng 2 - Khu Thường",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực thường tầng 2",
                            IsActive = true
                        },
                        new
                        {
                            Id = "AREA005",
                            AreaId = "A005",
                            AreaName = "Sân Thượng",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực sân thượng, không gian mở",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DishId")
                        .IsUnique();

                    b.HasIndex("KitchenId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = "DISH001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D001",
                            DishName = "Steak Bò Mỹ",
                            IsActive = true,
                            KitchenId = "KITCHEN001",
                            Price = 350000.0
                        },
                        new
                        {
                            Id = "DISH002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D002",
                            DishName = "Pasta Carbonara",
                            IsActive = true,
                            KitchenId = "KITCHEN001",
                            Price = 180000.0
                        },
                        new
                        {
                            Id = "DISH003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D003",
                            DishName = "Salmon Teriyaki",
                            IsActive = true,
                            KitchenId = "KITCHEN001",
                            Price = 280000.0
                        },
                        new
                        {
                            Id = "DISH004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D004",
                            DishName = "Phở Bò Đặc Biệt",
                            IsActive = true,
                            KitchenId = "KITCHEN002",
                            Price = 75000.0
                        },
                        new
                        {
                            Id = "DISH005",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D005",
                            DishName = "Bún Chả Hà Nội",
                            IsActive = true,
                            KitchenId = "KITCHEN002",
                            Price = 65000.0
                        },
                        new
                        {
                            Id = "DISH006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D006",
                            DishName = "Cơm Gà Hải Nam",
                            IsActive = true,
                            KitchenId = "KITCHEN002",
                            Price = 85000.0
                        },
                        new
                        {
                            Id = "DISH007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D007",
                            DishName = "Lẩu Thái Chua Cay",
                            IsActive = true,
                            KitchenId = "KITCHEN002",
                            Price = 250000.0
                        },
                        new
                        {
                            Id = "DISH008",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D008",
                            DishName = "Sườn Nướng BBQ",
                            IsActive = true,
                            KitchenId = "KITCHEN003",
                            Price = 195000.0
                        },
                        new
                        {
                            Id = "DISH009",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D009",
                            DishName = "Gà Nướng Mật Ong",
                            IsActive = true,
                            KitchenId = "KITCHEN003",
                            Price = 165000.0
                        },
                        new
                        {
                            Id = "DISH010",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D010",
                            DishName = "Bò Nướng Lá Lốt",
                            IsActive = true,
                            KitchenId = "KITCHEN003",
                            Price = 145000.0
                        },
                        new
                        {
                            Id = "DISH011",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D011",
                            DishName = "Tiramisu",
                            IsActive = true,
                            KitchenId = "KITCHEN004",
                            Price = 65000.0
                        },
                        new
                        {
                            Id = "DISH012",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D012",
                            DishName = "Chocolate Lava Cake",
                            IsActive = true,
                            KitchenId = "KITCHEN004",
                            Price = 75000.0
                        },
                        new
                        {
                            Id = "DISH013",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D013",
                            DishName = "Kem Vanilla Pháp",
                            IsActive = true,
                            KitchenId = "KITCHEN004",
                            Price = 45000.0
                        },
                        new
                        {
                            Id = "DISH014",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D014",
                            DishName = "Mojito Classic",
                            IsActive = true,
                            KitchenId = "KITCHEN005",
                            Price = 85000.0
                        },
                        new
                        {
                            Id = "DISH015",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D015",
                            DishName = "Cà Phê Sữa Đá",
                            IsActive = true,
                            KitchenId = "KITCHEN005",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = "DISH016",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D016",
                            DishName = "Sinh Tố Bơ",
                            IsActive = true,
                            KitchenId = "KITCHEN005",
                            Price = 35000.0
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Kitchens", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KitchenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId")
                        .IsUnique();

                    b.ToTable("Kitchens");

                    b.HasData(
                        new
                        {
                            Id = "KITCHEN001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên món Âu, Mỹ, Ý",
                            IsActive = true,
                            KitchenId = "K001",
                            KitchenName = "Bếp Âu"
                        },
                        new
                        {
                            Id = "KITCHEN002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên món Việt, Trung, Nhật, Hàn",
                            IsActive = true,
                            KitchenId = "K002",
                            KitchenName = "Bếp Á"
                        },
                        new
                        {
                            Id = "KITCHEN003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên các món nướng, BBQ",
                            IsActive = true,
                            KitchenId = "K003",
                            KitchenName = "Bếp Nướng BBQ"
                        },
                        new
                        {
                            Id = "KITCHEN004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên tráng miệng, đồ ngọt",
                            IsActive = true,
                            KitchenId = "K004",
                            KitchenName = "Bếp Dessert"
                        },
                        new
                        {
                            Id = "KITCHEN005",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên pha chế đồ uống, cocktail",
                            IsActive = true,
                            KitchenId = "K005",
                            KitchenName = "Bar & Thức Uống"
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.AreaDishPrices", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Areas", "Area")
                        .WithMany("AreaDishPrices")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Dishes", "Dish")
                        .WithMany("AreaDishPrices")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Kitchens", "Kitchen")
                        .WithMany("Dishes")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Areas", b =>
                {
                    b.Navigation("AreaDishPrices");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.Navigation("AreaDishPrices");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Kitchens", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
