// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Data.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250911092108_InitClean")]
    partial class InitClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Domain.Entities.AreaDishPrices", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CustomPrice")
                        .HasColumnType("float");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DishId");

                    b.ToTable("AreaDishPrices");

                    b.HasData(
                        new
                        {
                            Id = "ADP001-STATIC-ID-GUID-000000001",
                            AreaId = "A001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 350000.0,
                            DishId = "D001",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP002-STATIC-ID-GUID-000000002",
                            AreaId = "A001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 75000.0,
                            DishId = "D004",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP003-STATIC-ID-GUID-000000003",
                            AreaId = "A001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 65000.0,
                            DishId = "D011",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP004-STATIC-ID-GUID-000000004",
                            AreaId = "A001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 85000.0,
                            DishId = "D014",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP005-STATIC-ID-GUID-000000005",
                            AreaId = "A001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 25000.0,
                            DishId = "D015",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP006-STATIC-ID-GUID-000000006",
                            AreaId = "A002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 185250.0,
                            DishId = "D008",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP007-STATIC-ID-GUID-000000007",
                            AreaId = "A002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 156750.0,
                            DishId = "D009",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP008-STATIC-ID-GUID-000000008",
                            AreaId = "A002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 137750.0,
                            DishId = "D010",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP009-STATIC-ID-GUID-000000009",
                            AreaId = "A002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 199500.0,
                            DishId = "D027",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP010-STATIC-ID-GUID-000000010",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 402500.0,
                            DishId = "D001",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP011-STATIC-ID-GUID-000000011",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 207000.0,
                            DishId = "D002",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP012-STATIC-ID-GUID-000000012",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 322000.0,
                            DishId = "D003",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP013-STATIC-ID-GUID-000000013",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 287500.0,
                            DishId = "D007",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP014-STATIC-ID-GUID-000000014",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 437000.0,
                            DishId = "D021",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP015-STATIC-ID-GUID-000000015",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 71500.0,
                            DishId = "D011",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP016-STATIC-ID-GUID-000000016",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 82500.0,
                            DishId = "D012",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP017-STATIC-ID-GUID-000000017",
                            AreaId = "A003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 93500.0,
                            DishId = "D014",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP018-STATIC-ID-GUID-000000018",
                            AreaId = "A004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 75000.0,
                            DishId = "D004",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP019-STATIC-ID-GUID-000000019",
                            AreaId = "A004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 65000.0,
                            DishId = "D005",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP020-STATIC-ID-GUID-000000020",
                            AreaId = "A004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 85000.0,
                            DishId = "D006",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP021-STATIC-ID-GUID-000000021",
                            AreaId = "A004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 135000.0,
                            DishId = "D025",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP022-STATIC-ID-GUID-000000022",
                            AreaId = "A006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 24250.0,
                            DishId = "D015",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP023-STATIC-ID-GUID-000000023",
                            AreaId = "A006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 43650.0,
                            DishId = "D030",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP024-STATIC-ID-GUID-000000024",
                            AreaId = "A006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 160050.0,
                            DishId = "D022",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP025-STATIC-ID-GUID-000000025",
                            AreaId = "A007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 456000.0,
                            DishId = "D021",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP026-STATIC-ID-GUID-000000026",
                            AreaId = "A007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 384000.0,
                            DishId = "D024",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP027-STATIC-ID-GUID-000000027",
                            AreaId = "A007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 780000.0,
                            DishId = "D035",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "ADP028-STATIC-ID-GUID-000000028",
                            AreaId = "A007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomPrice = 114000.0,
                            DishId = "D031",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Areas", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AreaId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            AreaId = "A001",
                            AreaName = "Tầng Trệt - Khu A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực tầng trệt, phù hợp cho gia đình",
                            Id = "A001-STATIC-ID-GUID-000000000001",
                            IsActive = true
                        },
                        new
                        {
                            AreaId = "A002",
                            AreaName = "Tầng Trệt - Khu B",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực tầng trệt, gần cửa sổ",
                            Id = "A002-STATIC-ID-GUID-000000000002",
                            IsActive = true
                        },
                        new
                        {
                            AreaId = "A003",
                            AreaName = "Tầng 2 - Khu VIP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực VIP tầng 2, view đẹp",
                            Id = "A003-STATIC-ID-GUID-000000000003",
                            IsActive = true
                        },
                        new
                        {
                            AreaId = "A004",
                            AreaName = "Tầng 2 - Khu Thường",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực thường tầng 2",
                            Id = "A004-STATIC-ID-GUID-000000000004",
                            IsActive = true
                        },
                        new
                        {
                            AreaId = "A005",
                            AreaName = "Sân Thượng",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực sân thượng, không gian mở",
                            Id = "A005-STATIC-ID-GUID-000000000005",
                            IsActive = false
                        },
                        new
                        {
                            AreaId = "A006",
                            AreaName = "Tầng Trệt - Khu C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực yên tĩnh, phù hợp làm việc",
                            Id = "A006-STATIC-ID-GUID-000000000006",
                            IsActive = true
                        },
                        new
                        {
                            AreaId = "A007",
                            AreaName = "Tầng 3 - Private Room",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phòng riêng cho doanh nghiệp và tiệc nhỏ",
                            Id = "A007-STATIC-ID-GUID-000000000007",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.DishGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.ToTable("DishGroups");

                    b.HasData(
                        new
                        {
                            GroupId = "DG001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các món ăn khai vị, salad và appetizer",
                            GroupName = "Món Khai Vị",
                            Id = "DG001-STATIC-ID-GUID-00000000001",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = "DG002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các món ăn chính như steak, pasta, cơm, phở",
                            GroupName = "Món Chính",
                            Id = "DG002-STATIC-ID-GUID-00000000002",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = "DG003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các món nướng, BBQ và thịt nướng",
                            GroupName = "Món Nướng BBQ",
                            Id = "DG003-STATIC-ID-GUID-00000000003",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = "DG004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các món hải sản tươi sống",
                            GroupName = "Hải Sản",
                            Id = "DG004-STATIC-ID-GUID-00000000004",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = "DG005",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các món lẩu, nồi và ăn tập thể",
                            GroupName = "Lẩu & Nồi",
                            Id = "DG005-STATIC-ID-GUID-00000000005",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = "DG006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các món tráng miệng, bánh ngọt và dessert",
                            GroupName = "Tráng Miệng",
                            Id = "DG006-STATIC-ID-GUID-00000000006",
                            IsActive = true
                        },
                        new
                        {
                            GroupId = "DG007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đồ uống, cocktail, nước ép và cà phê",
                            GroupName = "Thức Uống",
                            Id = "DG007-STATIC-ID-GUID-00000000007",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.Property<string>("DishId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("BasePrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DishId");

                    b.HasIndex("GroupId");

                    b.HasIndex("KitchenId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = "D001",
                            BasePrice = 350000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Steak Bò Mỹ",
                            GroupId = "DG002",
                            Id = "D001-STATIC-ID-GUID-000000000001",
                            IsActive = true,
                            KitchenId = "K001"
                        },
                        new
                        {
                            DishId = "D002",
                            BasePrice = 180000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Pasta Carbonara",
                            GroupId = "DG002",
                            Id = "D002-STATIC-ID-GUID-000000000002",
                            IsActive = true,
                            KitchenId = "K001"
                        },
                        new
                        {
                            DishId = "D003",
                            BasePrice = 280000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Salmon Teriyaki",
                            GroupId = "DG002",
                            Id = "D003-STATIC-ID-GUID-000000000003",
                            IsActive = true,
                            KitchenId = "K001"
                        },
                        new
                        {
                            DishId = "D020",
                            BasePrice = 220000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Chicken Cordon Bleu",
                            GroupId = "DG002",
                            Id = "D020-STATIC-ID-GUID-000000000020",
                            IsActive = true,
                            KitchenId = "K001"
                        },
                        new
                        {
                            DishId = "D021",
                            BasePrice = 380000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Lamb Chop Rosemary",
                            GroupId = "DG002",
                            Id = "D021-STATIC-ID-GUID-000000000021",
                            IsActive = true,
                            KitchenId = "K001"
                        },
                        new
                        {
                            DishId = "D022",
                            BasePrice = 165000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Mushroom Risotto",
                            GroupId = "DG002",
                            Id = "D022-STATIC-ID-GUID-000000000022",
                            IsActive = true,
                            KitchenId = "K001"
                        },
                        new
                        {
                            DishId = "D004",
                            BasePrice = 75000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Phở Bò Đặc Biệt",
                            GroupId = "DG002",
                            Id = "D004-STATIC-ID-GUID-000000000004",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D005",
                            BasePrice = 65000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Bún Chả Hà Nội",
                            GroupId = "DG002",
                            Id = "D005-STATIC-ID-GUID-000000000005",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D006",
                            BasePrice = 85000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Cơm Gà Hải Nam",
                            GroupId = "DG002",
                            Id = "D006-STATIC-ID-GUID-000000000006",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D023",
                            BasePrice = 95000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Pad Thai Tôm",
                            GroupId = "DG002",
                            Id = "D023-STATIC-ID-GUID-000000000023",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D024",
                            BasePrice = 320000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Sushi Set Deluxe",
                            GroupId = "DG002",
                            Id = "D024-STATIC-ID-GUID-000000000024",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D025",
                            BasePrice = 135000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Ramen Tonkotsu",
                            GroupId = "DG002",
                            Id = "D025-STATIC-ID-GUID-000000000025",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D007",
                            BasePrice = 250000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Lẩu Thái Chua Cay",
                            GroupId = "DG005",
                            Id = "D007-STATIC-ID-GUID-000000000007",
                            IsActive = true,
                            KitchenId = "K002"
                        },
                        new
                        {
                            DishId = "D008",
                            BasePrice = 195000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Sườn Nướng BBQ",
                            GroupId = "DG003",
                            Id = "D008-STATIC-ID-GUID-000000000008",
                            IsActive = true,
                            KitchenId = "K003"
                        },
                        new
                        {
                            DishId = "D009",
                            BasePrice = 165000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Gà Nướng Mật Ong",
                            GroupId = "DG003",
                            Id = "D009-STATIC-ID-GUID-000000000009",
                            IsActive = true,
                            KitchenId = "K003"
                        },
                        new
                        {
                            DishId = "D010",
                            BasePrice = 145000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Bò Nướng Lá Lốt",
                            GroupId = "DG003",
                            Id = "D010-STATIC-ID-GUID-000000000010",
                            IsActive = true,
                            KitchenId = "K003"
                        },
                        new
                        {
                            DishId = "D026",
                            BasePrice = 185000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Chả Cá Lăng",
                            GroupId = "DG003",
                            Id = "D026-STATIC-ID-GUID-000000000026",
                            IsActive = true,
                            KitchenId = "K003"
                        },
                        new
                        {
                            DishId = "D027",
                            BasePrice = 210000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Thịt Nướng Hàn Quốc",
                            GroupId = "DG003",
                            Id = "D027-STATIC-ID-GUID-000000000027",
                            IsActive = true,
                            KitchenId = "K003"
                        },
                        new
                        {
                            DishId = "D011",
                            BasePrice = 65000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Tiramisu",
                            GroupId = "DG006",
                            Id = "D011-STATIC-ID-GUID-000000000011",
                            IsActive = true,
                            KitchenId = "K004"
                        },
                        new
                        {
                            DishId = "D012",
                            BasePrice = 75000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Chocolate Lava Cake",
                            GroupId = "DG006",
                            Id = "D012-STATIC-ID-GUID-000000000012",
                            IsActive = true,
                            KitchenId = "K004"
                        },
                        new
                        {
                            DishId = "D013",
                            BasePrice = 45000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Kem Vanilla Pháp",
                            GroupId = "DG006",
                            Id = "D013-STATIC-ID-GUID-000000000013",
                            IsActive = true,
                            KitchenId = "K004"
                        },
                        new
                        {
                            DishId = "D028",
                            BasePrice = 35000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Bánh Flan Caramel",
                            GroupId = "DG006",
                            Id = "D028-STATIC-ID-GUID-000000000028",
                            IsActive = true,
                            KitchenId = "K004"
                        },
                        new
                        {
                            DishId = "D029",
                            BasePrice = 55000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Panna Cotta Berry",
                            GroupId = "DG006",
                            Id = "D029-STATIC-ID-GUID-000000000029",
                            IsActive = true,
                            KitchenId = "K004"
                        },
                        new
                        {
                            DishId = "D014",
                            BasePrice = 85000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Mojito Classic",
                            GroupId = "DG007",
                            Id = "D014-STATIC-ID-GUID-000000000014",
                            IsActive = true,
                            KitchenId = "K005"
                        },
                        new
                        {
                            DishId = "D015",
                            BasePrice = 25000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Cà Phê Sữa Đá",
                            GroupId = "DG007",
                            Id = "D015-STATIC-ID-GUID-000000000015",
                            IsActive = true,
                            KitchenId = "K005"
                        },
                        new
                        {
                            DishId = "D016",
                            BasePrice = 35000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Sinh Tố Bơ",
                            GroupId = "DG007",
                            Id = "D016-STATIC-ID-GUID-000000000016",
                            IsActive = true,
                            KitchenId = "K005"
                        },
                        new
                        {
                            DishId = "D030",
                            BasePrice = 45000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Trà Đào Cam Sả",
                            GroupId = "DG007",
                            Id = "D030-STATIC-ID-GUID-000000000030",
                            IsActive = true,
                            KitchenId = "K005"
                        },
                        new
                        {
                            DishId = "D031",
                            BasePrice = 95000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Cocktail Passion Fruit",
                            GroupId = "DG007",
                            Id = "D031-STATIC-ID-GUID-000000000031",
                            IsActive = true,
                            KitchenId = "K005"
                        },
                        new
                        {
                            DishId = "D032",
                            BasePrice = 280000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Lẩu Bò Nhúng Dấm",
                            GroupId = "DG005",
                            Id = "D032-STATIC-ID-GUID-000000000032",
                            IsActive = true,
                            KitchenId = "K006"
                        },
                        new
                        {
                            DishId = "D033",
                            BasePrice = 220000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Lẩu Gà Lá Giang",
                            GroupId = "DG005",
                            Id = "D033-STATIC-ID-GUID-000000000033",
                            IsActive = true,
                            KitchenId = "K006"
                        },
                        new
                        {
                            DishId = "D034",
                            BasePrice = 195000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Nồi Cá Kho Tộ",
                            GroupId = "DG005",
                            Id = "D034-STATIC-ID-GUID-000000000034",
                            IsActive = true,
                            KitchenId = "K006"
                        },
                        new
                        {
                            DishId = "D035",
                            BasePrice = 650000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Tôm Hùm Nướng Phô Mai",
                            GroupId = "DG004",
                            Id = "D035-STATIC-ID-GUID-000000000035",
                            IsActive = true,
                            KitchenId = "K007"
                        },
                        new
                        {
                            DishId = "D036",
                            BasePrice = 420000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Cua Rang Me",
                            GroupId = "DG004",
                            Id = "D036-STATIC-ID-GUID-000000000036",
                            IsActive = true,
                            KitchenId = "K007"
                        },
                        new
                        {
                            DishId = "D037",
                            BasePrice = 380000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Cá Mú Hấp Gừng",
                            GroupId = "DG004",
                            Id = "D037-STATIC-ID-GUID-000000000037",
                            IsActive = true,
                            KitchenId = "K007"
                        },
                        new
                        {
                            DishId = "D038",
                            BasePrice = 85000.0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishName = "Nghêu Hấp Lá Chuối",
                            GroupId = "DG004",
                            Id = "D038-STATIC-ID-GUID-000000000038",
                            IsActive = true,
                            KitchenId = "K007"
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Kitchens", b =>
                {
                    b.Property<string>("KitchenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KitchenId");

                    b.ToTable("Kitchens");

                    b.HasData(
                        new
                        {
                            KitchenId = "K001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên món Âu, Mỹ, Ý",
                            Id = "K001-STATIC-ID-GUID-000000000001",
                            IsActive = true,
                            KitchenName = "Bếp Âu"
                        },
                        new
                        {
                            KitchenId = "K002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên món Việt, Trung, Nhật, Hàn",
                            Id = "K002-STATIC-ID-GUID-000000000002",
                            IsActive = true,
                            KitchenName = "Bếp Á"
                        },
                        new
                        {
                            KitchenId = "K003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên các món nướng, BBQ",
                            Id = "K003-STATIC-ID-GUID-000000000003",
                            IsActive = true,
                            KitchenName = "Bếp Nướng BBQ"
                        },
                        new
                        {
                            KitchenId = "K004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên tráng miệng, đồ ngọt",
                            Id = "K004-STATIC-ID-GUID-000000000004",
                            IsActive = true,
                            KitchenName = "Bếp Dessert"
                        },
                        new
                        {
                            KitchenId = "K005",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên pha chế đồ uống, cocktail",
                            Id = "K005-STATIC-ID-GUID-000000000005",
                            IsActive = true,
                            KitchenName = "Bar & Thức Uống"
                        },
                        new
                        {
                            KitchenId = "K006",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên các món lẩu, nồi và ăn tập thể",
                            Id = "K006-STATIC-ID-GUID-000000000006",
                            IsActive = true,
                            KitchenName = "Bếp Lẩu & Nồi"
                        },
                        new
                        {
                            KitchenId = "K007",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên chế biến hải sản tươi sống",
                            Id = "K007-STATIC-ID-GUID-000000000007",
                            IsActive = true,
                            KitchenName = "Bếp Hải Sản"
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryAreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("PrimaryAreaId");

                    b.HasIndex("TableSessionId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "ORD001",
                            CreatedAt = new DateTime(2025, 1, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Id = "ORD001-STATIC-ID-GUID-0000000001",
                            IsPaid = false,
                            OrderStatus = "Open",
                            PrimaryAreaId = "A001",
                            TotalAmount = 0.0
                        },
                        new
                        {
                            OrderId = "ORD002",
                            ClosedAt = new DateTime(2025, 1, 15, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 15, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Id = "ORD002-STATIC-ID-GUID-0000000002",
                            IsPaid = true,
                            OrderStatus = "Paid",
                            PrimaryAreaId = "A003",
                            TotalAmount = 0.0
                        },
                        new
                        {
                            OrderId = "ORD003",
                            CreatedAt = new DateTime(2025, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = "ORD003-STATIC-ID-GUID-0000000003",
                            IsPaid = false,
                            OrderStatus = "Open",
                            PrimaryAreaId = "A002",
                            TotalAmount = 0.0
                        },
                        new
                        {
                            OrderId = "ORD004",
                            CreatedAt = new DateTime(2025, 1, 15, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            Id = "ORD004-STATIC-ID-GUID-0000000004",
                            IsPaid = false,
                            OrderStatus = "Open",
                            PrimaryAreaId = "A002",
                            TotalAmount = 0.0
                        },
                        new
                        {
                            OrderId = "ORD005",
                            CreatedAt = new DateTime(2025, 1, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Id = "ORD005-STATIC-ID-GUID-0000000005",
                            IsPaid = false,
                            OrderStatus = "Open",
                            PrimaryAreaId = "A007",
                            TotalAmount = 0.0
                        },
                        new
                        {
                            OrderId = "ORD006",
                            ClosedAt = new DateTime(2025, 1, 14, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 14, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = "ORD006-STATIC-ID-GUID-0000000006",
                            IsPaid = true,
                            OrderStatus = "Paid",
                            PrimaryAreaId = "A003",
                            TotalAmount = 0.0
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderDetailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PriceSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TableId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TableId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = "OD001-STATIC-ID-GUID-0000000001",
                            AreaId = "A001",
                            DishId = "D001",
                            OrderDetailId = "OD001",
                            OrderId = "ORD001",
                            PriceSource = "Base",
                            Quantity = 2,
                            TableId = "T001",
                            UnitPrice = 350000.0
                        },
                        new
                        {
                            Id = "OD002-STATIC-ID-GUID-0000000002",
                            AreaId = "A001",
                            DishId = "D004",
                            OrderDetailId = "OD002",
                            OrderId = "ORD001",
                            PriceSource = "Base",
                            Quantity = 1,
                            TableId = "T001",
                            UnitPrice = 75000.0
                        },
                        new
                        {
                            Id = "OD015-STATIC-ID-GUID-0000000015",
                            AreaId = "A001",
                            DishId = "D015",
                            OrderDetailId = "OD015",
                            OrderId = "ORD001",
                            PriceSource = "Base",
                            Quantity = 3,
                            TableId = "T001",
                            UnitPrice = 25000.0
                        },
                        new
                        {
                            Id = "OD003-STATIC-ID-GUID-0000000003",
                            AreaId = "A003",
                            DishId = "D001",
                            OrderDetailId = "OD003",
                            OrderId = "ORD002",
                            PriceSource = "Custom",
                            Quantity = 1,
                            TableId = "T006",
                            UnitPrice = 402500.0
                        },
                        new
                        {
                            Id = "OD004-STATIC-ID-GUID-0000000004",
                            AreaId = "A003",
                            DishId = "D014",
                            OrderDetailId = "OD004",
                            OrderId = "ORD002",
                            PriceSource = "Custom",
                            Quantity = 2,
                            TableId = "T006",
                            UnitPrice = 93500.0
                        },
                        new
                        {
                            Id = "OD016-STATIC-ID-GUID-0000000016",
                            AreaId = "A003",
                            DishId = "D035",
                            OrderDetailId = "OD016",
                            OrderId = "ORD002",
                            PriceSource = "Base",
                            Quantity = 1,
                            TableId = "T006",
                            UnitPrice = 650000.0
                        },
                        new
                        {
                            Id = "OD005-STATIC-ID-GUID-0000000005",
                            AreaId = "A002",
                            DishId = "D008",
                            OrderDetailId = "OD005",
                            OrderId = "ORD003",
                            PriceSource = "Custom",
                            Quantity = 1,
                            TableId = "T004",
                            UnitPrice = 185250.0
                        },
                        new
                        {
                            Id = "OD006-STATIC-ID-GUID-0000000006",
                            AreaId = "A002",
                            DishId = "D015",
                            OrderDetailId = "OD006",
                            OrderId = "ORD003",
                            PriceSource = "Base",
                            Quantity = 3,
                            TableId = "T004",
                            UnitPrice = 25000.0
                        },
                        new
                        {
                            Id = "OD017-STATIC-ID-GUID-0000000017",
                            AreaId = "A002",
                            DishId = "D023",
                            OrderDetailId = "OD017",
                            OrderId = "ORD003",
                            PriceSource = "Base",
                            Quantity = 2,
                            TableId = "T004",
                            UnitPrice = 95000.0
                        },
                        new
                        {
                            Id = "OD007-STATIC-ID-GUID-0000000007",
                            AreaId = "A002",
                            DishId = "D027",
                            OrderDetailId = "OD007",
                            OrderId = "ORD004",
                            PriceSource = "Base",
                            Quantity = 2,
                            TableId = "T011",
                            UnitPrice = 210000.0
                        },
                        new
                        {
                            Id = "OD008-STATIC-ID-GUID-0000000008",
                            AreaId = "A002",
                            DishId = "D032",
                            OrderDetailId = "OD008",
                            OrderId = "ORD004",
                            PriceSource = "Base",
                            Quantity = 1,
                            TableId = "T011",
                            UnitPrice = 280000.0
                        },
                        new
                        {
                            Id = "OD018-STATIC-ID-GUID-0000000018",
                            AreaId = "A002",
                            DishId = "D030",
                            OrderDetailId = "OD018",
                            OrderId = "ORD004",
                            PriceSource = "Base",
                            Quantity = 4,
                            TableId = "T011",
                            UnitPrice = 45000.0
                        },
                        new
                        {
                            Id = "OD009-STATIC-ID-GUID-0000000009",
                            AreaId = "A007",
                            DishId = "D021",
                            OrderDetailId = "OD009",
                            OrderId = "ORD005",
                            PriceSource = "Base",
                            Quantity = 5,
                            TableId = "T016",
                            UnitPrice = 380000.0
                        },
                        new
                        {
                            Id = "OD010-STATIC-ID-GUID-0000000010",
                            AreaId = "A007",
                            DishId = "D024",
                            OrderDetailId = "OD010",
                            OrderId = "ORD005",
                            PriceSource = "Base",
                            Quantity = 3,
                            TableId = "T016",
                            UnitPrice = 320000.0
                        },
                        new
                        {
                            Id = "OD019-STATIC-ID-GUID-0000000019",
                            AreaId = "A007",
                            DishId = "D031",
                            OrderDetailId = "OD019",
                            OrderId = "ORD005",
                            PriceSource = "Base",
                            Quantity = 8,
                            TableId = "T016",
                            UnitPrice = 95000.0
                        },
                        new
                        {
                            Id = "OD011-STATIC-ID-GUID-0000000011",
                            AreaId = "A003",
                            DishId = "D036",
                            OrderDetailId = "OD011",
                            OrderId = "ORD006",
                            PriceSource = "Base",
                            Quantity = 2,
                            TableId = "T012",
                            UnitPrice = 420000.0
                        },
                        new
                        {
                            Id = "OD012-STATIC-ID-GUID-0000000012",
                            AreaId = "A003",
                            DishId = "D037",
                            OrderDetailId = "OD012",
                            OrderId = "ORD006",
                            PriceSource = "Base",
                            Quantity = 1,
                            TableId = "T012",
                            UnitPrice = 380000.0
                        },
                        new
                        {
                            Id = "OD013-STATIC-ID-GUID-0000000013",
                            AreaId = "A003",
                            DishId = "D011",
                            OrderDetailId = "OD013",
                            OrderId = "ORD006",
                            PriceSource = "Custom",
                            Quantity = 4,
                            TableId = "T012",
                            UnitPrice = 71500.0
                        },
                        new
                        {
                            Id = "OD014-STATIC-ID-GUID-0000000014",
                            AreaId = "A003",
                            DishId = "D014",
                            OrderDetailId = "OD014",
                            OrderId = "ORD006",
                            PriceSource = "Custom",
                            Quantity = 3,
                            TableId = "T012",
                            UnitPrice = 93500.0
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.OrderTable", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FromTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ToTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TableId");

                    b.ToTable("OrderTables");

                    b.HasData(
                        new
                        {
                            Id = "OT001-STATIC-ID-GUID-0000000001",
                            FromTime = new DateTime(2025, 1, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPrimary = true,
                            OrderId = "ORD001",
                            TableId = "T001"
                        },
                        new
                        {
                            Id = "OT002-STATIC-ID-GUID-0000000002",
                            FromTime = new DateTime(2025, 1, 15, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPrimary = true,
                            OrderId = "ORD002",
                            TableId = "T006",
                            ToTime = new DateTime(2025, 1, 15, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "OT003-STATIC-ID-GUID-0000000003",
                            FromTime = new DateTime(2025, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrimary = true,
                            OrderId = "ORD003",
                            TableId = "T004"
                        },
                        new
                        {
                            Id = "OT004-STATIC-ID-GUID-0000000004",
                            FromTime = new DateTime(2025, 1, 15, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            IsPrimary = true,
                            OrderId = "ORD004",
                            TableId = "T011"
                        },
                        new
                        {
                            Id = "OT005-STATIC-ID-GUID-0000000005",
                            FromTime = new DateTime(2025, 1, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPrimary = true,
                            OrderId = "ORD005",
                            TableId = "T016"
                        },
                        new
                        {
                            Id = "OT006-STATIC-ID-GUID-0000000006",
                            FromTime = new DateTime(2025, 1, 14, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrimary = true,
                            OrderId = "ORD006",
                            TableId = "T012",
                            ToTime = new DateTime(2025, 1, 14, 22, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Table", b =>
                {
                    b.Property<string>("TableId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableId");

                    b.HasAlternateKey("TableCode");

                    b.HasIndex("AreaId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = "T001",
                            AreaId = "A001",
                            Capacity = 4,
                            Id = "T001-STATIC-ID-GUID-000000000001",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T001",
                            TableName = "Bàn A1"
                        },
                        new
                        {
                            TableId = "T002",
                            AreaId = "A001",
                            Capacity = 6,
                            Id = "T002-STATIC-ID-GUID-000000000002",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T002",
                            TableName = "Bàn A2"
                        },
                        new
                        {
                            TableId = "T003",
                            AreaId = "A001",
                            Capacity = 2,
                            Id = "T003-STATIC-ID-GUID-000000000003",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T003",
                            TableName = "Bàn A3"
                        },
                        new
                        {
                            TableId = "T010",
                            AreaId = "A001",
                            Capacity = 8,
                            Id = "T010-STATIC-ID-GUID-000000000010",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T010",
                            TableName = "Bàn A4"
                        },
                        new
                        {
                            TableId = "T004",
                            AreaId = "A002",
                            Capacity = 4,
                            Id = "T004-STATIC-ID-GUID-000000000004",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T004",
                            TableName = "Bàn B1"
                        },
                        new
                        {
                            TableId = "T005",
                            AreaId = "A002",
                            Capacity = 8,
                            Id = "T005-STATIC-ID-GUID-000000000005",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T005",
                            TableName = "Bàn B2"
                        },
                        new
                        {
                            TableId = "T011",
                            AreaId = "A002",
                            Capacity = 6,
                            Id = "T011-STATIC-ID-GUID-000000000011",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T011",
                            TableName = "Bàn B3"
                        },
                        new
                        {
                            TableId = "T006",
                            AreaId = "A003",
                            Capacity = 6,
                            Id = "T006-STATIC-ID-GUID-000000000006",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T006",
                            TableName = "Bàn VIP 1"
                        },
                        new
                        {
                            TableId = "T007",
                            AreaId = "A003",
                            Capacity = 10,
                            Id = "T007-STATIC-ID-GUID-000000000007",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T007",
                            TableName = "Bàn VIP 2"
                        },
                        new
                        {
                            TableId = "T012",
                            AreaId = "A003",
                            Capacity = 12,
                            Id = "T012-STATIC-ID-GUID-000000000012",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T012",
                            TableName = "Bàn VIP 3"
                        },
                        new
                        {
                            TableId = "T008",
                            AreaId = "A004",
                            Capacity = 4,
                            Id = "T008-STATIC-ID-GUID-000000000008",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T008",
                            TableName = "Bàn T2-1"
                        },
                        new
                        {
                            TableId = "T009",
                            AreaId = "A004",
                            Capacity = 6,
                            Id = "T009-STATIC-ID-GUID-000000000009",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T009",
                            TableName = "Bàn T2-2"
                        },
                        new
                        {
                            TableId = "T013",
                            AreaId = "A004",
                            Capacity = 4,
                            Id = "T013-STATIC-ID-GUID-000000000013",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T013",
                            TableName = "Bàn T2-3"
                        },
                        new
                        {
                            TableId = "T014",
                            AreaId = "A006",
                            Capacity = 2,
                            Id = "T014-STATIC-ID-GUID-000000000014",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T014",
                            TableName = "Bàn C1"
                        },
                        new
                        {
                            TableId = "T015",
                            AreaId = "A006",
                            Capacity = 4,
                            Id = "T015-STATIC-ID-GUID-000000000015",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T015",
                            TableName = "Bàn C2"
                        },
                        new
                        {
                            TableId = "T016",
                            AreaId = "A007",
                            Capacity = 15,
                            Id = "T016-STATIC-ID-GUID-000000000016",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T016",
                            TableName = "Phòng Riêng 1"
                        },
                        new
                        {
                            TableId = "T017",
                            AreaId = "A007",
                            Capacity = 20,
                            Id = "T017-STATIC-ID-GUID-000000000017",
                            IsActive = true,
                            SortOrder = 0,
                            Status = "Available",
                            TableCode = "T017",
                            TableName = "Phòng Riêng 2"
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.TableSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpenedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SessionId");

                    b.HasIndex("TableId");

                    b.ToTable("TableSessions");

                    b.HasData(
                        new
                        {
                            SessionId = "TS001",
                            Id = "TS001-STATIC-ID-GUID-00000000001",
                            OpenAt = new DateTime(2025, 1, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OpenedBy = "Staff001",
                            Status = "Available",
                            TableId = "T001"
                        },
                        new
                        {
                            SessionId = "TS002",
                            CloseAt = new DateTime(2025, 1, 15, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            ClosedBy = "Staff002",
                            Id = "TS002-STATIC-ID-GUID-00000000002",
                            OpenAt = new DateTime(2025, 1, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            OpenedBy = "Staff001",
                            Status = "Closed",
                            TableId = "T006"
                        },
                        new
                        {
                            SessionId = "TS003",
                            Id = "TS003-STATIC-ID-GUID-00000000003",
                            OpenAt = new DateTime(2025, 1, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OpenedBy = "Staff003",
                            Status = "Available",
                            TableId = "T011"
                        },
                        new
                        {
                            SessionId = "TS004",
                            CloseAt = new DateTime(2025, 1, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ClosedBy = "Staff001",
                            Id = "TS004-STATIC-ID-GUID-00000000004",
                            OpenAt = new DateTime(2025, 1, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            OpenedBy = "Staff002",
                            Status = "Closed",
                            TableId = "T014"
                        },
                        new
                        {
                            SessionId = "TS005",
                            Id = "TS005-STATIC-ID-GUID-00000000005",
                            OpenAt = new DateTime(2025, 1, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            OpenedBy = "Staff004",
                            Status = "Available",
                            TableId = "T016"
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.AreaDishPrices", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Areas", "Area")
                        .WithMany("AreaDishPrices")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Dishes", "Dish")
                        .WithMany("AreaDishPrices")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.DishGroup", "DishGroup")
                        .WithMany("Dishes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Kitchens", "Kitchen")
                        .WithMany("Dishes")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DishGroup");

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Areas", "PrimaryArea")
                        .WithMany("PrimaryOrders")
                        .HasForeignKey("PrimaryAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.TableSession", "TableSession")
                        .WithMany("Orders")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PrimaryArea");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Areas", "Area")
                        .WithMany("OrderDetails")
                        .HasForeignKey("AreaId");

                    b.HasOne("Restaurant.Domain.Entities.Dishes", "Dish")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Table", "Table")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TableId");

                    b.Navigation("Area");

                    b.Navigation("Dish");

                    b.Navigation("Order");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.OrderTable", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Order", "Order")
                        .WithMany("OrderTables")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Table", "Table")
                        .WithMany("OrderTables")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Table", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Areas", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.TableSession", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Table", "Table")
                        .WithMany("TableSessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Areas", b =>
                {
                    b.Navigation("AreaDishPrices");

                    b.Navigation("OrderDetails");

                    b.Navigation("PrimaryOrders");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.DishGroup", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.Navigation("AreaDishPrices");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Kitchens", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderTables");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Table", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderTables");

                    b.Navigation("TableSessions");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.TableSession", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
