// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Data.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Domain.Entities.AreaDishPrices", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CustomPrice")
                        .HasColumnType("float");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DishId");

                    b.ToTable("AreaDishPrices");

                    b.HasData(
                        new
                        {
                            Id = "61945c0d-deff-4057-9e8a-f721a5c0cb7b",
                            AreaId = "bf1d3a14-cec7-4217-afef-3070cc964d2b",
                            CustomPrice = 350000.0,
                            DishId = "7a1e24dc-ca9e-4bf5-aa2d-c0036c4043fa",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "774bac0c-974a-402e-bf86-55112d3f7b32",
                            AreaId = "bf1d3a14-cec7-4217-afef-3070cc964d2b",
                            CustomPrice = 75000.0,
                            DishId = "d9ccfb52-47f7-47be-b8fe-f5eacac402b1",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "b9e21b5c-a1b9-40a2-a37c-2d54645772fd",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 402500.0,
                            DishId = "7a1e24dc-ca9e-4bf5-aa2d-c0036c4043fa",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "4326b2e6-74f3-4fb7-98ce-d93c603bb3ae",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 207000.0,
                            DishId = "5667d134-2d25-4a16-a5d1-157308227a17",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "88f46e3a-5ee1-4afc-b006-dda8a8ba613f",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 322000.0,
                            DishId = "eba3c6e2-a1c1-43ab-9d2a-33c13b335e65",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "e589b937-ce64-4a17-b37c-c3824ed536fa",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 287500.0,
                            DishId = "f40ac9ad-43af-4a54-86fe-f47ff0999b34",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "933b82d7-80b3-412a-9095-641178588217",
                            AreaId = "87cce1fb-d6f9-49a2-b026-15bb0740385c",
                            CustomPrice = 185250.0,
                            DishId = "6d2a44ca-6e63-472f-9d80-9cecd5ba8d04",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "5ebea2d1-85b2-444f-ad62-1333c379d38d",
                            AreaId = "87cce1fb-d6f9-49a2-b026-15bb0740385c",
                            CustomPrice = 156750.0,
                            DishId = "bfee412d-3269-45b4-b044-d57d1da9d9f0",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ab2daf7d-8b87-4c85-83be-caed26fdb0cd",
                            AreaId = "87cce1fb-d6f9-49a2-b026-15bb0740385c",
                            CustomPrice = 137750.0,
                            DishId = "1a3c182a-9605-44e1-ae27-df362a15494c",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "4780ada7-3329-4d75-9865-b01ad347348d",
                            AreaId = "e3da7474-bab3-48de-b4bd-7887170d7e59",
                            CustomPrice = 75000.0,
                            DishId = "d9ccfb52-47f7-47be-b8fe-f5eacac402b1",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "91dcdba4-88f7-4c1a-b030-fda2240684fd",
                            AreaId = "e3da7474-bab3-48de-b4bd-7887170d7e59",
                            CustomPrice = 65000.0,
                            DishId = "cff053a4-a929-40c7-ad66-dd4c3b8a6d65",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "5f7ad5cd-1aef-4152-a8d8-223aec2c5f52",
                            AreaId = "e3da7474-bab3-48de-b4bd-7887170d7e59",
                            CustomPrice = 85000.0,
                            DishId = "5c19bd27-58d1-4b05-9a68-cbf20ababb2c",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "aa4d00b3-42ab-4af8-9d04-c75a0ee08593",
                            AreaId = "bf1d3a14-cec7-4217-afef-3070cc964d2b",
                            CustomPrice = 65000.0,
                            DishId = "c6dc0e86-f5d0-45fc-b4de-d7299c581a33",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "45eafca6-f793-48de-8f0d-a19154392783",
                            AreaId = "bf1d3a14-cec7-4217-afef-3070cc964d2b",
                            CustomPrice = 85000.0,
                            DishId = "3d1559a8-bb69-4c03-b341-6df3035d5341",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "6ba71674-fa01-4ee0-abe8-40a9b707a47b",
                            AreaId = "bf1d3a14-cec7-4217-afef-3070cc964d2b",
                            CustomPrice = 25000.0,
                            DishId = "de57ba84-10b9-4ec3-84a7-7296917dd829",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "ca3797b3-d380-42a1-a25e-8a265d9e3988",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 71500.0,
                            DishId = "c6dc0e86-f5d0-45fc-b4de-d7299c581a33",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "31b9a1c7-2e62-4532-b11f-197644b732b7",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 82500.0,
                            DishId = "021d17c2-fc6a-459a-af8d-e38eeac64faa",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        },
                        new
                        {
                            Id = "36745970-4738-442d-81ac-7c757068102b",
                            AreaId = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            CustomPrice = 93500.0,
                            DishId = "3d1559a8-bb69-4c03-b341-6df3035d5341",
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Areas", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = "bf1d3a14-cec7-4217-afef-3070cc964d2b",
                            AreaId = "A001",
                            AreaName = "Tầng Trệt - Khu A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực tầng trệt, phù hợp cho gia đình",
                            IsActive = true
                        },
                        new
                        {
                            Id = "87cce1fb-d6f9-49a2-b026-15bb0740385c",
                            AreaId = "A002",
                            AreaName = "Tầng Trệt - Khu B",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực tầng trệt, gần cửa sổ",
                            IsActive = true
                        },
                        new
                        {
                            Id = "a57ca4df-4212-4271-ab4e-3c2761987e0b",
                            AreaId = "A003",
                            AreaName = "Tầng 2 - Khu VIP",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực VIP tầng 2, view đẹp",
                            IsActive = true
                        },
                        new
                        {
                            Id = "e3da7474-bab3-48de-b4bd-7887170d7e59",
                            AreaId = "A004",
                            AreaName = "Tầng 2 - Khu Thường",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực thường tầng 2",
                            IsActive = true
                        },
                        new
                        {
                            Id = "eb837d6c-079e-44b9-8df5-da3ac31bc03c",
                            AreaId = "A005",
                            AreaName = "Sân Thượng",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khu vực sân thượng, không gian mở",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = "7a1e24dc-ca9e-4bf5-aa2d-c0036c4043fa",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D001",
                            DishName = "Steak Bò Mỹ",
                            IsActive = true,
                            KitchenId = "2a8d7cbf-f8c0-426f-bebc-da0d67428aad",
                            Price = 350000.0
                        },
                        new
                        {
                            Id = "5667d134-2d25-4a16-a5d1-157308227a17",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D002",
                            DishName = "Pasta Carbonara",
                            IsActive = true,
                            KitchenId = "2a8d7cbf-f8c0-426f-bebc-da0d67428aad",
                            Price = 180000.0
                        },
                        new
                        {
                            Id = "eba3c6e2-a1c1-43ab-9d2a-33c13b335e65",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D003",
                            DishName = "Salmon Teriyaki",
                            IsActive = true,
                            KitchenId = "2a8d7cbf-f8c0-426f-bebc-da0d67428aad",
                            Price = 280000.0
                        },
                        new
                        {
                            Id = "d9ccfb52-47f7-47be-b8fe-f5eacac402b1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D004",
                            DishName = "Phở Bò Đặc Biệt",
                            IsActive = true,
                            KitchenId = "ed39caf8-325b-4670-a339-9a0b17983250",
                            Price = 75000.0
                        },
                        new
                        {
                            Id = "cff053a4-a929-40c7-ad66-dd4c3b8a6d65",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D005",
                            DishName = "Bún Chả Hà Nội",
                            IsActive = true,
                            KitchenId = "ed39caf8-325b-4670-a339-9a0b17983250",
                            Price = 65000.0
                        },
                        new
                        {
                            Id = "5c19bd27-58d1-4b05-9a68-cbf20ababb2c",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D006",
                            DishName = "Cơm Gà Hải Nam",
                            IsActive = true,
                            KitchenId = "ed39caf8-325b-4670-a339-9a0b17983250",
                            Price = 85000.0
                        },
                        new
                        {
                            Id = "f40ac9ad-43af-4a54-86fe-f47ff0999b34",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D007",
                            DishName = "Lẩu Thái Chua Cay",
                            IsActive = true,
                            KitchenId = "ed39caf8-325b-4670-a339-9a0b17983250",
                            Price = 250000.0
                        },
                        new
                        {
                            Id = "6d2a44ca-6e63-472f-9d80-9cecd5ba8d04",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D008",
                            DishName = "Sườn Nướng BBQ",
                            IsActive = true,
                            KitchenId = "dcabb860-de38-4cb8-a190-8ef255deba01",
                            Price = 195000.0
                        },
                        new
                        {
                            Id = "bfee412d-3269-45b4-b044-d57d1da9d9f0",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D009",
                            DishName = "Gà Nướng Mật Ong",
                            IsActive = true,
                            KitchenId = "dcabb860-de38-4cb8-a190-8ef255deba01",
                            Price = 165000.0
                        },
                        new
                        {
                            Id = "1a3c182a-9605-44e1-ae27-df362a15494c",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D010",
                            DishName = "Bò Nướng Lá Lốt",
                            IsActive = true,
                            KitchenId = "dcabb860-de38-4cb8-a190-8ef255deba01",
                            Price = 145000.0
                        },
                        new
                        {
                            Id = "c6dc0e86-f5d0-45fc-b4de-d7299c581a33",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D011",
                            DishName = "Tiramisu",
                            IsActive = true,
                            KitchenId = "f6729fb5-bf42-4a1c-9e5e-845f7964f71a",
                            Price = 65000.0
                        },
                        new
                        {
                            Id = "021d17c2-fc6a-459a-af8d-e38eeac64faa",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D012",
                            DishName = "Chocolate Lava Cake",
                            IsActive = true,
                            KitchenId = "f6729fb5-bf42-4a1c-9e5e-845f7964f71a",
                            Price = 75000.0
                        },
                        new
                        {
                            Id = "f985a4f6-43d3-4545-a967-7aba4556a108",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D013",
                            DishName = "Kem Vanilla Pháp",
                            IsActive = true,
                            KitchenId = "f6729fb5-bf42-4a1c-9e5e-845f7964f71a",
                            Price = 45000.0
                        },
                        new
                        {
                            Id = "3d1559a8-bb69-4c03-b341-6df3035d5341",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D014",
                            DishName = "Mojito Classic",
                            IsActive = true,
                            KitchenId = "8820e289-12fc-4434-820e-440479c9b462",
                            Price = 85000.0
                        },
                        new
                        {
                            Id = "de57ba84-10b9-4ec3-84a7-7296917dd829",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D015",
                            DishName = "Cà Phê Sữa Đá",
                            IsActive = true,
                            KitchenId = "8820e289-12fc-4434-820e-440479c9b462",
                            Price = 25000.0
                        },
                        new
                        {
                            Id = "1f86ddb0-3b7e-441f-9628-3bc7b2a7de9e",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DishId = "D016",
                            DishName = "Sinh Tố Bơ",
                            IsActive = true,
                            KitchenId = "8820e289-12fc-4434-820e-440479c9b462",
                            Price = 35000.0
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Kitchens", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KitchenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KitchenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kitchens");

                    b.HasData(
                        new
                        {
                            Id = "2a8d7cbf-f8c0-426f-bebc-da0d67428aad",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên món Âu, Mỹ, Ý",
                            IsActive = true,
                            KitchenId = "K001",
                            KitchenName = "Bếp Âu"
                        },
                        new
                        {
                            Id = "ed39caf8-325b-4670-a339-9a0b17983250",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên món Việt, Trung, Nhật, Hàn",
                            IsActive = true,
                            KitchenId = "K002",
                            KitchenName = "Bếp Á"
                        },
                        new
                        {
                            Id = "dcabb860-de38-4cb8-a190-8ef255deba01",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên các món nướng, BBQ",
                            IsActive = true,
                            KitchenId = "K003",
                            KitchenName = "Bếp Nướng BBQ"
                        },
                        new
                        {
                            Id = "f6729fb5-bf42-4a1c-9e5e-845f7964f71a",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên tráng miệng, đồ ngọt",
                            IsActive = true,
                            KitchenId = "K004",
                            KitchenName = "Bếp Dessert"
                        },
                        new
                        {
                            Id = "8820e289-12fc-4434-820e-440479c9b462",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuyên pha chế đồ uống, cocktail",
                            IsActive = true,
                            KitchenId = "K005",
                            KitchenName = "Bar & Thức Uống"
                        });
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.AreaDishPrices", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Areas", "Area")
                        .WithMany("AreaDishPrices")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Domain.Entities.Dishes", "Dish")
                        .WithMany("AreaDishPrices")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Kitchens", "Kitchen")
                        .WithMany("Dishes")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitchen");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Areas", b =>
                {
                    b.Navigation("AreaDishPrices");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Dishes", b =>
                {
                    b.Navigation("AreaDishPrices");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Kitchens", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
